repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        exclude: ^(alembic/|tests/)
        additional_dependencies: []
        args: [--ignore-missing-imports]